version: '3'
services:
  tm.mysql:
    container_name: tm_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config/etc:/etc/mysql/conf.d
      - ./mysql/backups:/opt/data
    ports:
      - '3307:3306'
  tm.admin.api:
    container_name: tm_admin_api
    build:
      context: ./node/admin_api
      dockerfile: Dockerfile
    env_file:
      - config/admin_api/.env
    volumes:
      - ./node/admin_api:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/uploads
    ports:
      - '4000:4000'
    environment:
      MYSQL_USER: 'root' 
      MYSQL_PASSWORD: 'password' 
      MYSQL_DATABASE: 'tm' 
      MYSQL_HOST: 'tm.mysql' 
    links:
      - tm.mysql:db
    depends_on: 
      - tm.mysql
  tm.admin.web:
    container_name: tm_admin_web
    build:
      context: ./node/admin_web
      dockerfile: Dockerfile
    volumes:
      - ./node/admin_web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4001:8080'
    links:
      - tm.admin.api:api
    depends_on: 
      - tm.admin.api
    environment:
      - npm_config_unsafe_perm=true
  tm.site.web:
    container_name: tm_site_web
    build:
      context: ./node/site_web
      dockerfile: Dockerfile
    volumes:
      - ./node/site_web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4002:8080'
    environment:
      - npm_config_unsafe_perm=true
networks:
  default:
    external:
      name: tm-network